In [3]:
import torch

# 畳み込みフィルター1と2の重み行列を定義
filter1 = torch.Tensor([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

filter2 = torch.Tensor([
    [21, 22, 23],
    [24, 25, 26],
    [27, 28, 29]
])

filter3 = torch.Tensor([
    [31, 32, 33],
    [34, 35, 36],
    [37, 38, 39]
])

# 重み行列を1次元ベクトルに変換
filter1_1d = filter1.view(-1)
filter2_1d = filter2.view(-1)
filter3_1d = filter3.view(-1)

# 1次元ベクトルを結合
combined_filter = torch.cat((filter1_1d, filter2_1d), dim=0)

# 結果を表示
print(combined_filter)


tensor([11., 12., 13., 14., 15., 16., 17., 18., 19., 21., 22., 23., 24., 25.,
        26., 27., 28., 29.])


In [4]:
import torch

# 畳み込みフィルター1と2の重み行列を定義
filter1 = torch.Tensor([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

filter2 = torch.Tensor([
    [21, 22, 23],
    [24, 25, 26],
    [27, 28, 29]
])

# フィルターを1次元化して交互に結合
combined_filter = torch.cat((filter1.view(-1), filter2.view(-1)), dim=0)

# 結果を表示
print(combined_filter)


tensor([11., 12., 13., 14., 15., 16., 17., 18., 19., 21., 22., 23., 24., 25.,
        26., 27., 28., 29.])


In [7]:
import torch

# 畳み込みフィルター1と2の重み行列を定義
filter1 = torch.Tensor([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

filter2 = torch.Tensor([
    [21, 22, 23],
    [24, 25, 26],
    [27, 28, 29]
])
filter3 = torch.Tensor([
    [31, 32, 33],
    [34, 35, 36],
    [37, 38, 39]
])

# フィルターを1次元化して交互に結合
filter1_1d = filter1.view(-1)
filter2_1d = filter2.view(-1)
filter3_1d = filter3.view(-1)
combined_filter = torch.empty(filter1_1d.size(0) + filter2_1d.size(0) + + filter3_1d.size(0))

combined_filter[0::3] = filter1_1d
combined_filter[1::3] = filter2_1d
combined_filter[2::3] = filter3_1d


# 結果を表示
print(combined_filter)


tensor([11., 21., 31., 12., 22., 32., 13., 23., 33., 14., 24., 34., 15., 25.,
        35., 16., 26., 36., 17., 27., 37., 18., 28., 38., 19., 29., 39.])


tensor([[8*8のデータ],[8*8のデータ],[8*8のデータ],[8*8のデータ],[8*8のデータ]])

tensor([[8*8*5のデータ]])

In [8]:
import torch

def flatten_filters(*filters):
    # フィルターの数
    num_filters = len(filters)
    
    # 各フィルターを1次元化してリストに格納
    flattened_filters = [filter.view(-1) for filter in filters]

    # フィルターを交互に結合
    combined_filter = torch.empty(flattened_filters[0].size(0) * num_filters)

    for i in range(num_filters):
        combined_filter[i::num_filters] = flattened_filters[i]

    return combined_filter

In [10]:
# 畳み込みフィルターを定義
filter1 = torch.Tensor([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19],
    [110, 111, 122]
])

filter2 = torch.Tensor([
    [21, 22, 23],
    [24, 25, 26],
    [27, 28, 29],
    [210, 211, 222] 
])

filter3 = torch.Tensor([
    [31, 32, 33],
    [34, 35, 36],
    [37, 38, 39],
    [310, 311, 322]
])

# フィルターを1次元化し、結合
combined_filter = flatten_filters(filter1, filter2, filter3)

# 結果を表示
print(combined_filter)

tensor([ 11.,  21.,  31.,  12.,  22.,  32.,  13.,  23.,  33.,  14.,  24.,  34.,
         15.,  25.,  35.,  16.,  26.,  36.,  17.,  27.,  37.,  18.,  28.,  38.,
         19.,  29.,  39., 110., 210., 310., 111., 211., 311., 122., 222., 322.])


In [18]:
import torch

def flatten_and_alternate_concat(*filters):
    num_filters = len(filters)
    
    # フィルターを1次元化してリストに格納
    flattened_filters = [filter.view(-1) for filter in filters]
    
    # フィルターを交互に結合
    combined_filter = torch.cat([f.view(1, -1) for f in torch.stack(flattened_filters, dim=1)], dim=1)

    return combined_filter

In [22]:
# テスト用のデータを作成（torch.Size([1, 5, 8, 8])）
test_data = torch.randn(1, 5, 8, 8)

print(test_data)

tensor([[[[-2.6701e-01, -1.9354e+00, -3.1917e-01,  6.2122e-01,  2.4129e+00,
           -1.2880e+00,  8.2800e-02,  2.0404e+00],
          [-1.8164e+00, -3.6378e-01, -9.2980e-01, -1.2961e+00,  5.0139e-01,
           -7.6025e-01, -1.0156e+00,  4.4169e-01],
          [-7.2218e-01,  1.2364e+00, -9.8822e-01, -1.0810e+00, -9.6646e-01,
            1.6692e+00,  1.1800e+00,  9.3439e-01],
          [-7.4766e-01, -4.5581e-01,  8.2272e-01,  7.1888e-01,  1.4744e-01,
           -1.2395e+00, -7.2316e-01, -6.4046e-01],
          [ 1.3427e-01, -5.7002e-01, -6.8061e-01, -9.1965e-01, -1.4127e-01,
           -5.3215e-01,  4.2303e-02,  7.7104e-01],
          [-1.1378e+00, -2.3674e+00, -5.0441e-01,  1.4700e-01, -2.7650e-01,
            3.3413e-01, -1.0885e+00, -4.2227e-01],
          [ 9.0451e-03,  1.1878e+00,  3.5549e-01, -5.9742e-03, -9.6737e-01,
           -5.2265e-01,  7.2607e-01,  8.7835e-02],
          [-7.9853e-01,  1.7093e+00,  9.0035e-01,  6.3968e-01, -4.6087e-01,
            4.7054e-01, -3.5528e-01

In [23]:
# データを1次元化し、指定した形状に変換
result = flatten_and_alternate_concat(test_data)

# 結果の形状を表示
print(result)  # torch.Size([1, 320])

tensor([[-2.6701e-01, -1.9354e+00, -3.1917e-01,  6.2122e-01,  2.4129e+00,
         -1.2880e+00,  8.2800e-02,  2.0404e+00, -1.8164e+00, -3.6378e-01,
         -9.2980e-01, -1.2961e+00,  5.0139e-01, -7.6025e-01, -1.0156e+00,
          4.4169e-01, -7.2218e-01,  1.2364e+00, -9.8822e-01, -1.0810e+00,
         -9.6646e-01,  1.6692e+00,  1.1800e+00,  9.3439e-01, -7.4766e-01,
         -4.5581e-01,  8.2272e-01,  7.1888e-01,  1.4744e-01, -1.2395e+00,
         -7.2316e-01, -6.4046e-01,  1.3427e-01, -5.7002e-01, -6.8061e-01,
         -9.1965e-01, -1.4127e-01, -5.3215e-01,  4.2303e-02,  7.7104e-01,
         -1.1378e+00, -2.3674e+00, -5.0441e-01,  1.4700e-01, -2.7650e-01,
          3.3413e-01, -1.0885e+00, -4.2227e-01,  9.0451e-03,  1.1878e+00,
          3.5549e-01, -5.9742e-03, -9.6737e-01, -5.2265e-01,  7.2607e-01,
          8.7835e-02, -7.9853e-01,  1.7093e+00,  9.0035e-01,  6.3968e-01,
         -4.6087e-01,  4.7054e-01, -3.5528e-01,  1.3780e-01,  6.2228e-01,
         -6.3597e-01, -2.0688e+00, -3.

In [21]:
import torch

def flatten_and_alternate_concat(*filters):
    num_filters = len(filters)
    
    # フィルターを1次元化してリストに格納
    flattened_filters = [filter.view(-1) for filter in filters]
    
    # フィルターを交互に結合
    combined_filter = torch.cat([f.view(1, -1) for f in torch.stack(flattened_filters, dim=1)], dim=1)

    return combined_filter

# テスト用のフィルターを定義
filter1 = torch.Tensor([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

filter2 = torch.Tensor([
    [21, 22, 23],
    [24, 25, 26],
    [27, 28, 29]
])

filter3 = torch.Tensor([
    [31, 32, 33],
    [34, 35, 36],
    [37, 38, 39]
])

# フィルターを1次元化し、交互に結合
combined_filter = flatten_and_alternate_concat(filter1, filter2, filter3)

# 結果を表示
print(combined_filter)


tensor([[11., 21., 31., 12., 22., 32., 13., 23., 33., 14., 24., 34., 15., 25.,
         35., 16., 26., 36., 17., 27., 37., 18., 28., 38., 19., 29., 39.]])


In [25]:
import torch

# 元のデータを作成 (torch([1, 320]))
original_data = torch.randn(1, 320)

# 偶数番目のデータを抽出して新しいテンソルを作成 (torch([1, 160]))
even_data = original_data[0, 0::2].view(1, -1)

print(original_data)
# 結果を表示



tensor([[ 1.3528e+00,  2.9980e-01, -4.7247e-01, -1.0726e+00,  1.6317e+00,
         -2.2510e-01, -4.1541e-01, -2.1207e-01,  4.8574e-01, -6.1425e-01,
          1.0089e-01, -6.7232e-01,  1.2156e+00,  1.8401e+00, -2.2124e+00,
         -1.5496e+00, -3.9939e-01,  3.6271e-02, -1.4196e-01,  1.1901e+00,
         -2.0063e+00, -8.2373e-01, -2.8194e+00,  2.6263e-01,  9.9966e-01,
         -1.7225e+00,  3.3447e-01, -1.9764e+00,  9.2849e-01, -1.9869e-01,
          1.7284e+00,  5.8596e-01,  2.5495e+00,  1.2488e-02,  1.2404e+00,
          6.8477e-01,  5.2931e-01,  2.0498e+00, -1.5514e+00,  5.1792e-01,
         -3.0646e-01, -1.4711e+00,  2.4393e+00,  4.7667e-01, -2.1435e+00,
         -7.9897e-01, -3.9049e-01, -1.7606e+00, -5.9211e-02, -3.8960e-01,
          6.4984e-02, -6.3882e-01, -1.0092e-01, -1.0540e+00,  7.6979e-01,
         -5.0726e-01, -2.6844e+00, -2.4251e+00,  6.0348e-01, -4.9100e-01,
          4.3382e-01,  4.3231e-01, -4.3493e-01,  6.9734e-01, -5.0168e-01,
         -2.7653e-01,  7.4402e-01, -1.

In [27]:
import torch

def flatten_input(input_data):
    # 入力データを1次元化
    flatten_data = input_data.view(1, -1)
    no0 = flatten_data[0, 0::64].view(1,-1)
    no1 = flatten_data[0, 1::64].view(1,-1)
    no2 = flatten_data[0, 2::64].view(1,-1)
    no3 = flatten_data[0, 3::64].view(1,-1)
    no4 = flatten_data[0, 4::64].view(1,-1)
    flatten_data_x = torch.cat((no0, no1, no2, no3, no4), dim=0)
    return flatten_data_x

# テスト用の入力データを作成 (torch.Size([1, 5, 8, 8]))
test_data = torch.randn(1, 5, 8, 8)

In [33]:
import torch

def flatten_input(input_data, num_tensors=64):
    # 入力データを1次元化
    flatten_data = input_data.view(1, -1)
    
    # テンソルを生成してリストに格納
    tensor_list = [flatten_data[0, i::num_tensors].view(1, -1) for i in range(num_tensors)]
    
    # テンソルを連結 (dim=0を使用して縦方向に連結)
    flatten_data_x = torch.cat(tensor_list, dim=0)
    
    return flatten_data_x

# テスト用の入力データを作成 (torch.Size([1, 320]))
test_data = torch.randn(1, 5, 8, 8)

# no0からno99までのテンソルを生成して連結
result = flatten_input(test_data, 64)

# 結果を表示
print(result)


tensor([[ 1.1012e+00,  7.6482e-01, -1.1846e+00, -7.7533e-01, -4.6919e-01],
        [ 1.1308e+00,  5.7037e-01, -9.4367e-01, -1.0793e+00, -2.6246e+00],
        [ 1.1530e-01,  4.0734e-01,  1.4273e+00, -1.1089e+00, -8.5820e-01],
        [ 8.8393e-01,  4.6550e-01,  9.5375e-01, -1.5298e+00,  4.5870e-02],
        [-7.4528e-01,  1.1559e+00, -6.5156e-02, -5.3868e-02,  8.1576e-01],
        [ 1.3802e+00,  3.6939e-02,  1.1944e+00,  1.0388e+00,  5.1267e-02],
        [ 1.4254e+00, -9.8779e-03, -2.1566e+00, -8.9384e-01, -4.8784e-02],
        [ 7.7892e-01, -6.8401e-02,  3.1230e-02, -6.3605e-01,  1.5140e+00],
        [ 5.6777e-01, -7.4739e-01,  6.8299e-01, -1.0570e-01,  2.6103e-02],
        [ 2.7049e-01,  7.5310e-02,  1.8565e+00,  3.6578e-01, -1.0208e+00],
        [-1.2751e+00, -2.2249e+00, -1.9173e-01,  1.8114e-01, -1.4603e+00],
        [-7.0133e-01, -1.1543e+00,  1.7564e+00, -1.6675e-01,  4.0644e-02],
        [-6.3019e-01, -1.7664e+00, -7.2973e-02, -1.0597e-01, -6.0369e-01],
        [-3.8184e-01,  3.

In [34]:
test_data

tensor([[[[ 1.1012e+00,  1.1308e+00,  1.1530e-01,  8.8393e-01, -7.4528e-01,
            1.3802e+00,  1.4254e+00,  7.7892e-01],
          [ 5.6777e-01,  2.7049e-01, -1.2751e+00, -7.0133e-01, -6.3019e-01,
           -3.8184e-01,  6.0698e-01, -1.7807e+00],
          [ 1.0823e+00,  8.3036e-01, -1.4418e+00, -1.4813e+00,  7.9099e-01,
           -2.2741e+00, -3.8773e-01, -7.7092e-02],
          [ 8.6801e-01,  1.1772e+00, -2.0175e-01, -5.8033e-03,  5.3432e-03,
            1.1064e+00, -3.2498e-01,  1.3682e+00],
          [ 1.2411e+00,  6.5453e-01, -9.1523e-02,  7.9492e-01, -2.1854e-01,
            1.3107e+00,  1.1083e+00, -1.4169e+00],
          [-6.0002e-01,  8.4689e-01,  8.3604e-01, -2.0423e+00,  1.7329e+00,
           -5.2364e-01, -5.8900e-01,  8.1103e-01],
          [ 4.1466e-01, -4.5513e-01,  4.5157e-01,  1.8791e+00, -1.2292e+00,
            1.0188e-01,  1.3037e+00,  1.1484e+00],
          [ 2.1996e-02,  4.0938e-01,  4.1785e-01, -5.2521e-01, -7.6398e-01,
            4.3767e-01, -2.0977e+00

In [29]:
A = flatten_input(test_data)
A

tensor([[ 0.9727, -1.2219,  1.4417,  2.2902,  0.5324],
        [ 0.4456, -1.3297, -0.8060, -0.7373, -0.4390],
        [-1.2967, -0.6820,  1.9854,  1.1865,  0.8631],
        [ 0.2092,  2.4459,  0.6518, -0.8865, -0.6348],
        [-0.2934, -0.5168,  0.0579,  1.1639,  1.5165]])